### ISSUE TITLE
Bad interaction with python-mode for pdb

### ISSUE THREAD

**Issue by sulami** [synic/jbeans-emacs#12]
I'm running spacemacs with the stock Python layer config. Because it wants to highlights `pdb` lines black text on yellow, with the current line highlighted (in dark gray), the `pdb` lines becomes essentially unreadable when the cursor is on it. Not a huge issue, but somewhat annoying.

**Comment by synic** [comment]
Haha, you are correct.  I've noticed it too, but I've been too lazy to fix it, but now that someone else has noticed, I guess I better do something about it.

The problem is that the current line background is dark, but the text on the ipdb line is black. So, I think for it to be visible, the text has to be yellow or something.

I have an idea.  I will give it a try ...

**Comment by synic** [comment]
Ok, I made a change.  It should be up on melpa in a bit.  Let me know if that works for you.

**Comment by sulami** [comment]
Works amazingly, many thanks! ❤️
